const INTEGRATIONS = [
    {
        id: 'apple-music',
        label: 'Scan Apple Music',
        btnClass: 'bg-[#ff4e6b] hover:bg-[#e6334f] pl-11',
        scanBtnClass: 'bg-[#ff4e6b] hover:bg-[#e6334f]',
        icon: '/apple-music-icon.svg',
        iconStyle: { left: '16px', height: '20px', width: '20px' },
        placeholder: 'https://music.apple.com/ua/playlist/...',
        endpoint: '/api/scan/apple-music',
        type: 'url',
    },
    {
        id: 'deezer',
        label: 'Scan Deezer',
        btnClass: 'bg-[#A238FF] hover:bg-[#8a2de6] pl-11',
        scanBtnClass: 'bg-[#A238FF] hover:bg-[#8a2de6]',
        icon: '/deezer-icon.png',
        iconStyle: { left: '16px', height: '20px', width: '20px' },
        placeholder: 'https://www.deezer.com/en/playlist/...',
        endpoint: '/api/scan/deezer',
        type: 'url',
    },
    {
        id: 'soundcloud',
        label: 'Scan SoundCloud',
        btnClass: 'bg-[#FF5500] hover:bg-[#e64d00] pl-11',
        scanBtnClass: 'bg-[#FF5500] hover:bg-[#e64d00]',
        icon: '/soundcloud-icon.png',
        iconStyle: { left: '8px', height: 'auto', width: '35px' },
        placeholder: 'https://soundcloud.com/.../sets/...',
        endpoint: '/api/scan/soundcloud',
        type: 'url',
    },
    {
        id: 'spotify',
        label: 'Scan Spotify',
        btnClass: 'bg-[#1ED760] hover:bg-[#1abc54] pl-11',
        icon: '/spotify-icon.svg',
        iconStyle: { left: '16px', height: '20px', width: '20px' },
        type: 'guide',
    },
    {
        id: 'rekordbox',
        label: 'Scan rekordbox',
        btnClass: 'bg-[#000000] hover:bg-[#222222] pl-11',
        icon: '/rekordbox-icon.png',
        iconStyle: { left: '16px', height: '20px', width: 'auto' },
        type: 'guide',
    },
    {
        id: 'youtube',
        label: 'Scan YouTube Music',
        btnClass: 'bg-[#FF0033] hover:bg-[#cc0029] pl-[54px]',
        scanBtnClass: 'bg-[#FF0033] hover:bg-[#cc0029]',
        icon: '/youtube-icon.png',
        iconStyle: { left: '16px', height: 'auto', width: '31px' },
        placeholder: 'https://music.youtube.com/playlist?list=...',
        endpoint: '/api/scan/youtube',
        type: 'url',
    },
];

export default INTEGRATIONS;
